# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(221F23)
$foreground = rgb(F7DFD8)
$color0 = rgb(49454A)
$color1 = rgb(24152A)
$color2 = rgb(50262A)
$color3 = rgb(563264)
$color4 = rgb(633973)
$color5 = rgb(9C4A74)
$color6 = rgb(AD7B6B)
$color7 = rgb(EBC9BF)
$color8 = rgb(A48D85)
$color9 = rgb(301C38)
$color10 = rgb(6A3338)
$color11 = rgb(734286)
$color12 = rgb(844C99)
$color13 = rgb(D0639B)
$color14 = rgb(E7A48F)
$color15 = rgb(EBC9BF)
