# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

windowrule = match:tag browser, opacity 1.0 0.9
windowrule = match:tag projects, opacity 1.0 0.8
windowrule = match:tag im, opacity 1.0 0.86
windowrule = match:tag multimedia, opacity 1.0 0.86
windowrule = match:tag file-manager, opacity 1.0 0.8
windowrule = match:tag terminal, opacity 1.0 0.9
windowrule = match:tag settings, opacity 1.0 0.8
windowrule = match:tag viewer, opacity 1.0 0.75
windowrule = match:tag wallpaper, opacity 1.0 0.8
windowrule = match:class ^(gedit|org.gnome.TextEditor|mousepad)$, opacity 1.0 0.7
windowrule = match:class ^(deluge)$, opacity 1.0 0.8
windowrule = match:class ^(seahorse)$, opacity 1.0 0.8
windowrule = match:title ^(Picture-in-Picture)$, opacity 1.0 0.75
windowrule = match:fullscreen true, rounding 0
